export const TASK_TIMELINE_INITIAL_LIMIT = 64;
export const TASK_TIMELINE_HISTORY_LIMIT = 160;
export const TASK_TIMELINE_INITIAL_BYTE_LIMIT = 256 * 1024;
export const TASK_TIMELINE_HISTORY_BYTE_LIMIT = 512 * 1024;
export const TASK_TIMELINE_SINGLE_EVENT_BYTE_LIMIT = 64 * 1024;
export const TASK_TIMELINE_MAX_PAGE_LIMIT = 600;
export const TASK_TIMELINE_MAX_PAGE_BYTE_LIMIT = 2 * 1024 * 1024;
export const TASK_TIMELINE_MAX_SINGLE_EVENT_BYTE_LIMIT = 256 * 1024;
export const TASK_TIMELINE_PAYLOAD_PREVIEW_CHARS = 4096;

export const TASK_TIMELINE_CACHE_TASK_LIMIT = 5;
export const TASK_TIMELINE_CACHE_BYTE_LIMIT = 4 * 1024 * 1024;
export const TASK_EVENT_DETAIL_CACHE_BYTE_LIMIT = 4 * 1024 * 1024;
